[package]
name = "dre-ip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["p256_impl"]
p256_impl = ["sha2", "p256"]

[dependencies.num-bigint]
version = "0.4.3"
features = ["serde"]

[dependencies.p256]
version = "0.10.0"
optional = true
features = ["arithmetic", "ecdsa-core", "ecdsa", "serde"]

[dependencies.rand]
version = "0.8.4"

[dependencies.sha2]
version = "0.10.1"
optional = true
