[package]
name = "dre-ip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.num-bigint]
version = "0.4.3"
features = ["serde"]

[dependencies.p256]
version = "0.10.0"
features = ["arithmetic", "ecdsa-core", "ecdsa", "serde"]

[dependencies.serde]
version = "1.0.133"
features = ["derive"]
